pasteleria/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_page, name= 'home'),
    path('about_us/', views.about_us, name='about'),

]

pasteleria/pasteleria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('products/', include('products.urls')),
    path('registro/', include("registro.urls")),
    path('login_out/', include("login_out.urls")),
    


    

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pasteleria/products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.productList, name='products'),
    path('post/<int:id>', views.detail, name='post_detail'),
    path('addProduct', views.addProduct, name='add_product'),
    path('editProduct/<int:id>', views.editProduct, name='edit_product'),
    path('deleteProduct/<int:id>', views.deleteProduct, name='delete_product'),
    path('post/<int:id>/addComment', views.addComment, name='add_comment'),


]

pasteleria/products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Products(models.Model):
    title = models.CharField(max_length=200, null=True)
    subtitle = models.CharField(max_length=200, null=True)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    add_time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='postpic', null=True, blank=True)

    

    def __str__(self):
        return self.title + ' | ' + str(self.author)



class Comments(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Products, related_name='comments', on_delete=models.CASCADE, null=True)
    add_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + ' | ' + str(self.post)

pasteleria/products/forms.py
from dataclasses import fields
from django import forms
from products.models import Products, Comments



class ProductForm(forms.ModelForm):

    class Meta:
        model = Products
        fields = ['title', 'subtitle', 'image', 'body']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ['title', 'body']

pasteleria/products/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from products.models import Products, Comments
from django.contrib.auth.decorators import login_required
from products.forms import ProductForm, CommentForm
from datetime import datetime




# Create your views here.

def productList(request):
    products = Products.objects.all()

    return render(request, 'products.html', {'products': products})



def detail(request, id):
    products = Products.objects.filter(id=id)

    return render(request, 'detail.html', {'products': products})




@login_required
def addProduct(request):
    if request.method == 'POST':

        my_form = ProductForm(request.POST, request.FILES)
        if my_form.is_valid():

            post = my_form.save(commit=False)
            post.author = request.user
            post.save()

            return redirect('products')

        return render(request, 'addProduct.html', {'my_form': my_form})
    return render(request, 'addProduct.html')




@login_required
def editProduct(request, id):
    product = get_object_or_404(Products, id=id)
    if request.method == 'POST':

        my_form = ProductForm(request.POST, request.FILES, instance=product)
        if my_form.is_valid():

            product = my_form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect('products')
    else:
        my_form = ProductForm(instance=product)
    return render(request, 'editProduct.html', {'my_form': my_form})



@login_required
def deleteProduct(request, id):
    product = Products.objects.filter(id=id)
    product.delete()

    return redirect('products')




@login_required
def addComment(request, id):
    products = get_object_or_404(Products, id=id)

    #my_form = CommentForm(instance=products)
    if request.method == 'POST':
        my_form = CommentForm(request.POST)

        if my_form.is_valid():
    
            comment = my_form.save(commit=False)
            comment.author = request.user
            comment.post = products
            comment.save()
            return redirect('post_detail', id=products.id)
        else:
            return HttpResponse(f'mal')
    else:
        my_form = CommentForm()

    return render(request, 'addComment.html', {'my_form': my_form})

pasteleria/products/templates/addComment.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
  <title>Add Comment Page</title>
{% endblock %}

{% block body %}


<h2>Add a comment</h2>
<div class="container">
    <form class="create-form" action="" method="POST">
        {% csrf_token %}
        <div class="form-group my-4">
            <label for="id_title">Title</label>
            <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
        </div>
      
        <div class="form-group my-4">
            <label for="id_body">Body</label>
            <textarea class="form-control" type="text" name="body" id="id_body" rows="3" placeholder="Write something..." required></textarea>
        </div>
      
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <button class="submit-button btn btn-dark btn-block me-md-2" type="submit">Post</button>
        </div>
        
      </form>
</div>

{% endblock %}

pasteleria/products/templates/addProduct.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
    <title>Add Products Page</title>
{% endblock %}

{% block body %}
<div class="container my-4">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <h3>ADD PRODUCT</h3>
            <form class="create-form" action="addProduct" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group my-4">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                </div>

                <div class="form-group my-4">
                    <label for="id_subtitle">Subtitle</label>
                    <input class="form-control" type="text" name="subtitle" id="id_subtitle" placeholder="Subtitle" required autofocus>
                </div>

                <div class="form-group my-4">
                    <label for="id_body">Body</label>
                    <textarea class="form-control" type="text" name="body" id="id_body" rows="3" placeholder="Write something..." required></textarea>
                </div>

                <div class="form-group my-4">
                    <label for="id_image">Image</label>
                    <input type="file" name="image" id="id_image" accept="image/*">
                </div>

                <button class="submit-button btn btn-dark btn-block" type="submit">Post</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

pasteleria/products/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
  <title>Detail Page</title>
{% endblock %}

{% block body %}

<div class="container">
  {% for product in products %}

  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a class="btn btn-dark me-md-2 my-4" href="{% url 'edit_product' product.id %}" role="button">Edit</a>
    <a class="btn btn-dark me-md-2 my-4" href="{% url 'delete_product' product.id %}" role="button">Delete</a>
  </div>

  <h2 class="my-4">{{product.title}}</h2>
  <h5>{{product.subtitle}}</h5>   
  <p>
    <span class="mr-4">By: {{product.author}} | {{product.add_time}}</span>
  </p>
  <br>
  <img src="{{ product.image.url }}" alt="">
  <p>{{product.body}}</p>
  
  <h2>Comments</h2><a class="btn btn-dark me-md-2 my-4" href="{% url 'add_comment' product.id %}" role="button">+ Add a Comment</a>

  {% if not product.comments.all %}
    <p>Be the first to comment!</p>

  {% else %}
    {% for comment in product.comments.all %}
      <article>
        <ul>
          <li>
              <strong>{{comment.author}} | {{comment.title}} on {{comment.add_time}}</strong><br>
              {{comment.body}}
          </li>
        </ul>
      </article>
  
    {% endfor %}
  {% endif %}



  <a class="btn btn-dark my-4" href="{% url 'products' %}">  ← Back</a>

  {% endfor %}
</div>
{% endblock body %}

pasteleria/products/templates/editProduct.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
    <title>Edit Products Page</title>
{% endblock %}

{% block body %}
<div class="container my-4">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <h3>EDIT PRODUCT</h3>
            <form class="create-form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group my-4">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" required autofocus>
                </div>

                <div class="form-group my-4">
                    <label for="id_subtitle">Subtitle</label>
                    <input class="form-control" type="text" name="subtitle" id="id_subtitle" required autofocus>
                </div>

                <div class="form-group my-4">
                    <label for="id_body">Body</label>
                    <textarea class="form-control" type="text" name="body" id="id_body" rows="3" required></textarea>
                </div>

                <div class="form-group my-4">
                    <label for="id_image">Image</label>
                    <input type="file" name="image" id="id_image" accept="image/*">
                </div>

                <button class="submit-button btn btn-dark btn-block" type="submit">Edit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pasteleria/products/templates/products.html
{% extends 'base.html'%}
{% load static %}

{% block title%}
  <title>Products Page</title>
{% endblock %}

{% block body %}
<div class="container py-5">

  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a class="btn btn-dark me-md-2 my-4" href="{% url 'add_product' %}" role="button"> + Add product</a>
  </div>

  {% for product in products %}
  <div class="card mb-3">
    <div class="card-body">
      <h4 class="card-title"><a href="{% url 'post_detail' product.id %}">{{product.title}}</a></h4>
      <p class="card-text">{{product.subtitle}}</p>
      <p class="mr-2">Author: {{product.author}}</p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock body %}